### ISSUE TITLE
Make tags customizable easily

### ISSUE THREAD

**Issue by cg-cnu** [cg-cnu/vscode-codetags#1]
Hello, i use the codetag extension, and i want to customize them, in the documentation you say i can do this in tags.ts, but i don`t know where i have to put the file to work. help me please! - [@zelljhos](https://twitter.com/zelljhos)

**Comment by zhubeilife** [comment]
Yes, I also like this extension very much. But I can't find the tags.ts file?

**Comment by cg-cnu** [comment]
Hey @zhubeilife Sorry for the delay! The latest version of extension is out with the ability to add custom tags and some nice improvements. Test it and let me know if you got any comments or suggestions! 😃

**Comment by cg-cnu** [comment]
Hey guys! I guess, its working fine now. Am closing this one. 
Feel free to open a new issue if you have any suggestions! 🙂
