### ISSUE TITLE
Tags.ts file - Where ?

### ISSUE THREAD

**Issue by SheepDomination** [cg-cnu/vscode-codetags#2]
Where is the tags.ts file ?

**Comment by cg-cnu** [comment]
Hey @SheepDomination Sorry for the confusion. I am in the plans of re writing the extension to not use tags.ts file and create custom tags using the user settings. Finally its done and version 0.1.0 is out. 
Try it out and let me know if you got any feedback.

**Comment by SheepDomination** [comment]
This is great but I couldn't find in the documentation on how to use or setup custom tags ?

**Comment by cg-cnu** [comment]
Hey I wrote down the instructions in readme! Am writing detailed steps here... 

* open users / workspace settings in your vscode
* Add the custom tags like this...
<img src="https://user-images.githubusercontent.com/2767425/39125245-f27179d0-471b-11e8-9b31-b5727060b641.gif" />
* Restart your vscode
* Your custom tag should be available like the default ones...
    <img src="https://user-images.githubusercontent.com/2767425/39125283-0c598086-471c-11e8-9919-1881b1c363d7.gif" />

**Comment by SheepDomination** [comment]
How do you get intelliSense to work with your extension ?

**Comment by cg-cnu** [comment]
If you are talking about the intellisense in workspace settings...
You need to provide your extension contributions...

```
"contributes": {
    "configuration": [
      {
        "properties": {
          "codetags.custom": {
            "type": "array",
            "description": "create custom codetags",
            "items": {
              "type": "object",
              "title": "codetag properties",
              "properties": {
                "name": {
                  "type": "string",
                  "title": "name",
                  "description": "codetag name"
                },
                "body": {
                  "type": "string",
                  "title": "body",
                  "description": "codetag body"
                }
              }
            }
          }
        }
      }
    ],
    "commands": [
      {
        "command": "codetags.tags",
        "title": "codetags"
      }
    ]
  },
```

and vscode will take care of it...

**Comment by SheepDomination** [comment]
How do you get the extension contributions by `vscode.workspace.getConfiguration('myExtension')` ?

**Comment by cg-cnu** [comment]
Am @SheepDomination I think this issue is resolved. Am closing it. 
Feel free to create a new issue if you have any questions or ideas! Thanks! 😄
