### ISSUE TITLE
list tags 

### ISSUE THREAD

**Issue by cg-cnu** [cg-cnu/vscode-codetags#3]
> will it be able to look at all TODO (or other) tags within a folder/workspace?
--- [twitter](https://twitter.com/ThisTNTSquid/status/989220634063335424)

Similar addon, but limited to TODO
https://github.com/MattiasPernhult/vscode-todo
https://github.com/kantlove/vscode-todo-parser

Discussion on a similar note...
https://github.com/Microsoft/vscode/issues/19963

**Comment by TheryFouchter** [comment]
Did it with [Todo Tree](https://marketplace.visualstudio.com/items?itemName=Gruntfuggly.todo-tree) !

Here is [the gist](https://gist.github.com/TheryFouchter/11dee8e56475339f75e7115b939af2ad).

**Comment by cg-cnu** [comment]
Wow! That's some great work @TheryFouchter 👏  Do you think it would be a good idea to create an end to end experience in Codetags extension itself by taking inspiration from those extensions ?

**Comment by TheryFouchter** [comment]
Sorry I'm kinda busy these days :/

Sure! I haven't seen any good extension made for these tags in mind. It would be a great contribution to the community :)

**Comment by TheryFouchter** [comment]
Just got a random idea,
If you have an ui to list tags, you could sort them by creation date based on the date in the tag.
This could be useful for tags like fixme / todo and could be good informations for the ui to notify the user.

- The first problem is that be the date can change to an unknown format.
- The second is that the default format in the tag is not [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) compliant.

Maybe using git blame as a first approach and them the date in the tag as a backup.

**Comment by cg-cnu** [comment]
These are some great ideas @TheryFouchter Let's do a quick mockup in a branch and see how it goes. Thanks for your interest 👍

**Comment by cg-cnu** [comment]
Hi @TheryFouchter For now I decided to just keep this addon small enough for the codetags use case and use Todo Tree and Better Comments as suggested in your gist. Thanks for the contribution. Cheers!
