### ISSUE TITLE
Keyboard Shortcut??

### ISSUE THREAD

**Issue by cycle4passion** [cg-cnu/vscode-codetags#4]
I know Command Palette access ( ctrl vs command-shift-p), but would be nice to have keyboard shortcut directly taking you to tag selection options, or auto create TO DO, etc.

**Comment by cg-cnu** [comment]
Am not a huge fan of keyboard shortcuts, especially for things which are not frequently used.
As it is there are ton of shortcuts we need to remember 😄  But, if you feel its gonna help! Let me know I can add the customization. Thanks for your inputs!
